name: Ubuntu 22.04

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        shared: [OFF]
        cxx: [g++-12]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup deps
        run: sudo apt-get install ninja-build libwayland-dev libxrandr-dev libxkbcommon-x11-dev libxinerama-dev libxcursor-dev libxi-dev  libglu1-mesa-dev freeglut3-dev mesa-common-dev libopenvr-dev
      - name: Prepare
        run: cmake  -DBUILD_SHARED_LIBS=${{matrix.shared}} -G Ninja -B build
        env:
          CXX: ${{matrix.cxx}}
      - name: Build
        run: cmake --build build -j=4
      - name: Test
        run: ctest --output-on-failure --test-dir build